# Generated by Django 3.2.4 on 2021-10-02 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('cpic', models.ImageField(default='', upload_to='static/city')),
                ('cdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=200)),
                ('gpic', models.ImageField(default='', upload_to='static/gallery')),
                ('gdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='guider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('guiderpic', models.ImageField(default='', upload_to='static/guider/')),
                ('qualification', models.CharField(max_length=100)),
                ('gid', models.CharField(max_length=30)),
                ('gidp', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=1000)),
                ('gdate', models.DateField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.cities')),
            ],
        ),
        migrations.CreateModel(
            name='addplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptitle', models.CharField(max_length=200)),
                ('baplace', models.CharField(max_length=400)),
                ('pdes', models.TextField(max_length=5000)),
                ('placepic', models.ImageField(default='', upload_to='static/place')),
                ('pdate', models.DateField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.cities')),
            ],
        ),
    ]
